(()=>{'use strict';const $=id=>document.getElementById(id);const state={voices:[],device:null,profiles:[],referencePath:'',sourcePath:'',stemSourcePath:'',poll:null};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.error||`HTTP ${r.status}`);return d}function setStatus(text,pct=0){$('generationStatus').textContent=text;$('progressBar').style.width=`${Math.max(0,Math.min(100,pct))}%`}
function tabs(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.tab));});}
async function boot(){tabs();try{const h=await api('/api/health');$('enginePill').classList.add('ok');$('enginePill').querySelector('span').textContent=h.ace_ready?'Engine ready':'Engine online · ACE starting';}catch(e){$('enginePill').querySelector('span').textContent='Engine unavailable';return}try{const [v,d,p]=await Promise.all([api('/api/voices'),api('/api/device'),api('/api/model-profiles')]);state.voices=v.voices||[];state.device=d;state.profiles=p.profiles||[];renderVoices();renderDevice();renderModels();}catch(e){console.error(e)}loadProjects();}
function renderVoices(){const sel=$('voiceSelect');sel.innerHTML=state.voices.map(v=>`<option value="${esc(v.id)}">${esc(v.name)}</option>`).join('');const grid=$('voiceGrid');grid.innerHTML=state.voices.map(v=>`<div class="voice-card" data-voice="${esc(v.id)}"><b>${esc(v.name)}</b><small>${esc(v.descriptor)}</small></div>`).join('');grid.querySelectorAll('[data-voice]').forEach(c=>c.onclick=()=>{sel.value=c.dataset.voice;const v=state.voices.find(x=>x.id===c.dataset.voice);if(v)$('seed').value=v.seed;grid.querySelectorAll('.voice-card').forEach(x=>x.classList.toggle('selected',x===c));});const first=state.voices[0];if(first){sel.value=first.id;$('seed').value=first.seed}}
function renderDevice(){const d=state.device;$('deviceInfo').textContent=JSON.stringify(d,null,2);$('recommendedProfile').innerHTML=`<b>${esc(d.recommended?.label||'Compatibility')}</b><p class="muted">${esc(d.recommended?.notes||'')}</p>`;if(d.max_duration)$('duration').max=d.max_duration;}
function renderModels(){const current=state.device?.recommended?.id;$('modelGrid').innerHTML=state.profiles.map(p=>`<article class="model-card ${p.id===current?'current':''}"><span>${esc(p.id.toUpperCase())}</span><h3>${esc(p.label)}</h3><p>${esc(p.model)}${p.lm?` + ${esc(p.lm)}`:''}</p><p>${esc(p.notes)}</p><button class="secondary" data-download="${esc(p.model)}">Prepare model</button></article>`).join('');document.querySelectorAll('[data-download]').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='Starting download…';try{const d=await api('/api/models/download',{method:'POST',body:JSON.stringify({model:b.dataset.download})});b.textContent=d.started?'Download started':'Already available / queued'}catch(e){b.textContent=e.message}setTimeout(()=>{b.disabled=false},1500)});}
$('promptChips')?.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{$('prompt').value=($('prompt').value.trim()+', '+b.dataset.add).replace(/^, /,'')});
$('voiceSelect')?.addEventListener('change',()=>{const v=state.voices.find(x=>x.id===$('voiceSelect').value);if(v&&$('voiceLock').checked)$('seed').value=v.seed});
async function upload(input,kind){const f=input.files?.[0];if(!f)return '';const fd=new FormData();fd.append('file',f);fd.append('kind',kind);const r=await fetch('/api/upload',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Upload failed');return d.path;}
async function poll(taskId,target='results'){clearInterval(state.poll);setStatus('Queued / running…',15);const tick=async()=>{try{const d=await api(`/api/jobs/${encodeURIComponent(taskId)}`);if(d.status===0){setStatus(d.progress_text||'Generating locally…',Math.min(90,20+(d.progress||0)*70));return}clearInterval(state.poll);state.poll=null;if(d.status===2){setStatus('Generation failed',0);renderError(target,d.error||'Generation failed');return}setStatus('Finished',100);renderResults(target,d.items||[]);loadProjects();}catch(e){clearInterval(state.poll);state.poll=null;setStatus('Polling error',0);renderError(target,e.message)}};await tick();if(!state.poll)state.poll=setInterval(tick,2200)}
function renderError(target,msg){$(target).innerHTML=`<div class="empty status-error">${esc(msg)}</div>`}
function renderResults(target,items){if(!items.length){renderError(target,'No output item returned.');return}$(target).innerHTML=items.map((it,i)=>`<article class="result-card"><b>Result ${i+1}</b><audio controls src="${esc(it.audio_url||'')}"></audio><div class="result-meta"><span>${esc(it.metas?.bpm||'—')} BPM</span><span>${esc(it.metas?.keyscale||'—')}</span><span>${esc(it.metas?.duration||'—')} sec</span><span>seed ${esc(it.seed_value||'—')}</span></div><p class="muted">${esc(it.prompt||'')}</p><a class="secondary" href="${esc(it.audio_url||'#')}" download>Download audio</a></article>`).join('')}
$('generateBtn').onclick=async()=>{const btn=$('generateBtn');btn.disabled=true;try{if($('referenceAudio').files?.[0]){if(!$('referenceConsent').checked)throw new Error('Confirm rights/consent before using reference audio.');state.referencePath=await upload($('referenceAudio'),'reference')}const v=state.voices.find(x=>x.id===$('voiceSelect').value);const body={prompt:$('prompt').value,lyrics:$('lyrics').value,auto_lyrics:$('autoLyrics').checked,instrumental:$('instrumental').checked,voice_id:v?.id||'',language:$('language').value,duration:Number($('duration').value),bpm:Number($('bpm').value),key_scale:$('key').value,time_signature:$('meter').value,quality:$('quality').value,variants:Number($('variants').value),seed:Number($('seed').value),voice_lock:$('voiceLock').checked,structure:$('structure').value,instruments:$('instruments').value,mood_journey:$('moodJourney').value,creation_mode:$('creationMode').value,reference_audio_path:state.referencePath,reference_consent:$('referenceConsent').checked};setStatus('Submitting to local model…',8);const d=await api('/api/generate',{method:'POST',body:JSON.stringify(body)});if(!d.task_id)throw new Error('Local engine did not return a task id.');await poll(d.task_id,'results')}catch(e){setStatus('Could not start',0);renderError('results',e.message)}finally{btn.disabled=false}};
$('cancelPoll').onclick=()=>{clearInterval(state.poll);state.poll=null;setStatus('Polling stopped',0)};
$('uploadSource').onclick=async()=>{try{state.sourcePath=await upload($('sourceAudio'),'source');$('sourcePath').textContent=state.sourcePath||'No source loaded'}catch(e){$('sourcePath').textContent=e.message}};
$('runEdit').onclick=async()=>{try{if(!state.sourcePath)throw new Error('Load source audio first.');const d=await api('/api/edit',{method:'POST',body:JSON.stringify({task_type:$('editTask').value,src_audio_path:state.sourcePath,prompt:$('editPrompt').value,repainting_start:Number($('editStart').value),repainting_end:Number($('editEnd').value),repaint_strength:Number($('editStrength').value),quality:$('editQuality').value})});await poll(d.task_id,'editResult')}catch(e){renderError('editResult',e.message)}};
$('uploadStemSource').onclick=async()=>{try{state.stemSourcePath=await upload($('stemSource'),'source');$('stemSourcePath').textContent=state.stemSourcePath||'No source loaded'}catch(e){$('stemSourcePath').textContent=e.message}};
$('runStem').onclick=async()=>{try{if(!state.stemSourcePath)throw new Error('Load source audio first.');const d=await api('/api/stem',{method:'POST',body:JSON.stringify({task_type:$('stemTask').value,src_audio_path:state.stemSourcePath,target_track:$('targetTrack').value,prompt:$('stemPrompt').value})});await poll(d.task_id,'stemResult')}catch(e){renderError('stemResult',e.message)}};
async function loadProjects(){try{const d=await api('/api/projects');const items=d.projects||[];$('projectGrid').innerHTML=items.length?items.map(p=>`<article class="project-card"><span>${esc(p.created_at||'')}</span><h3>${esc(p.title||'RIVANI song')}</h3><p>${esc(p.prompt||'')}</p>${p.audio_url?`<a href="${esc(p.audio_url)}">Open audio</a>`:''}</article>`).join(''):'<div class="empty">No local projects yet.</div>'}catch(e){$('projectGrid').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}$('refreshProjects').onclick=loadProjects;
const mixState={tracks:[],ctx:null,sources:[]};
function addMixTrack(file=null){const id=crypto.randomUUID?.()||String(Date.now()+Math.random());const row=document.createElement('div');row.className='mix-track';row.dataset.id=id;row.innerHTML=`<div><input type="file" accept="audio/*"><div class="track-name">Empty track</div></div><label>Vol<input class="track-vol" type="range" min="0" max="1.5" step=".01" value="1"></label><label>Pan<input class="track-pan" type="range" min="-1" max="1" step=".05" value="0"></label><button class="track-mute">Mute</button>`;$('mixTracks').appendChild(row);const rec={id,row,file:null,buffer:null,muted:false};mixState.tracks.push(rec);const inp=row.querySelector('input[type=file]');inp.onchange=()=>{rec.file=inp.files?.[0]||null;rec.buffer=null;row.querySelector('.track-name').textContent=rec.file?.name||'Empty track'};row.querySelector('.track-mute').onclick=()=>{rec.muted=!rec.muted;row.querySelector('.track-mute').textContent=rec.muted?'Unmute':'Mute';row.querySelector('.track-mute').classList.toggle('status-error',rec.muted)};}
$('addMixTrack').onclick=()=>addMixTrack();addMixTrack();
function fxVals(){return{low:Number($('lowEq').value),mid:Number($('midEq').value),high:Number($('highEq').value),comp:Number($('comp').value)/100,sat:Number($('sat').value)/100,reverb:Number($('reverb').value)/100,delay:Number($('delay').value)/100,width:Number($('width').value)/100,out:Number($('outputGain').value)}}
[['lowEq','lowEqVal',' dB'],['midEq','midEqVal',' dB'],['highEq','highEqVal',' dB'],['comp','compVal','%'],['sat','satVal','%'],['reverb','revVal','%'],['delay','delayVal','%'],['width','widthVal','%'],['outputGain','outVal',' dB']].forEach(([i,o,s])=>$(i).oninput=()=>$(o).textContent=$(i).value+s);
const presets={clean:{low:0,mid:0,high:1,comp:30,sat:4,reverb:8,delay:0,width:105,out:-1},warm:{low:2,mid:1,high:-1,comp:38,sat:16,reverb:12,delay:3,width:105,out:-1},punchy:{low:2,mid:1,high:2,comp:55,sat:10,reverb:7,delay:0,width:110,out:-.5},loud:{low:1,mid:0,high:1,comp:68,sat:12,reverb:5,delay:0,width:105,out:-.2},cinematic:{low:2,mid:-1,high:2,comp:42,sat:8,reverb:28,delay:8,width:135,out:-1}};
$('applyPreset').onclick=()=>{const p=presets[$('masterPreset').value]||presets.clean;[['lowEq','low'],['midEq','mid'],['highEq','high'],['comp','comp'],['sat','sat'],['reverb','reverb'],['delay','delay'],['width','width'],['outputGain','out']].forEach(([id,k])=>{$(id).value=p[k];$(id).dispatchEvent(new Event('input'))})};
async function decodeTracks(ctx){const active=mixState.tracks.filter(t=>t.file&&!t.muted);if(!active.length)throw new Error('Add at least one audio file to the mixer.');for(const t of active){if(!t.buffer){const ab=await t.file.arrayBuffer();t.buffer=await ctx.decodeAudioData(ab.slice(0))}}return active}
function curve(amount=0){const n=44100,c=new Float32Array(n),k=amount*120;for(let i=0;i<n;i++){const x=i*2/n-1;c[i]=(1+k)*x/(1+k*Math.abs(x))}return c}
function impulse(ctx,seconds=2.2,decay=2.2){const len=Math.floor(ctx.sampleRate*seconds),b=ctx.createBuffer(2,len,ctx.sampleRate);for(let ch=0;ch<2;ch++){const d=b.getChannelData(ch);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,decay)}return b}
function buildMaster(ctx,dest){const v=fxVals();const input=ctx.createGain();const low=ctx.createBiquadFilter();low.type='lowshelf';low.frequency.value=180;low.gain.value=v.low;const mid=ctx.createBiquadFilter();mid.type='peaking';mid.frequency.value=1200;mid.Q.value=.7;mid.gain.value=v.mid;const high=ctx.createBiquadFilter();high.type='highshelf';high.frequency.value=6000;high.gain.value=v.high;const sat=ctx.createWaveShaper();sat.curve=curve(v.sat);sat.oversample='2x';const comp=ctx.createDynamicsCompressor();comp.threshold.value=-10-v.comp*18;comp.ratio.value=2+v.comp*8;comp.attack.value=.01;comp.release.value=.18;const dry=ctx.createGain(),wet=ctx.createGain(),conv=ctx.createConvolver();conv.buffer=impulse(ctx);dry.gain.value=1-v.reverb*.55;wet.gain.value=v.reverb;const sum=ctx.createGain();const delay=ctx.createDelay(1);delay.delayTime.value=.28;const feedback=ctx.createGain();feedback.gain.value=Math.min(.55,v.delay*.65);const delayWet=ctx.createGain();delayWet.gain.value=v.delay;const master=ctx.createGain();master.gain.value=Math.pow(10,v.out/20);input.connect(low).connect(mid).connect(high).connect(sat).connect(comp);comp.connect(dry).connect(sum);comp.connect(conv).connect(wet).connect(sum);sum.connect(master);sum.connect(delay);delay.connect(feedback).connect(delay);delay.connect(delayWet).connect(master);master.connect(dest);return input}
async function previewMix(){stopMix();const ctx=new (window.AudioContext||window.webkitAudioContext)();mixState.ctx=ctx;const tracks=await decodeTracks(ctx);const master=buildMaster(ctx,ctx.destination);const now=ctx.currentTime+.05;tracks.forEach(t=>{const src=ctx.createBufferSource(),g=ctx.createGain(),pan=ctx.createStereoPanner();src.buffer=t.buffer;g.gain.value=Number(t.row.querySelector('.track-vol').value);pan.pan.value=Number(t.row.querySelector('.track-pan').value);src.connect(g).connect(pan).connect(master);src.start(now);mixState.sources.push(src)});$('mixStatus').textContent=`Previewing ${tracks.length} track(s) with local Web Audio FX.`}
function stopMix(){mixState.sources.forEach(s=>{try{s.stop()}catch{}});mixState.sources=[];if(mixState.ctx){mixState.ctx.close().catch(()=>{});mixState.ctx=null}}
$('mixPreview').onclick=()=>previewMix().catch(e=>$('mixStatus').textContent=e.message);$('mixStop').onclick=stopMix;
function encodeWav(buffer){const ch=buffer.numberOfChannels,len=buffer.length*ch*2,ab=new ArrayBuffer(44+len),v=new DataView(ab);let o=0;const s=x=>{for(let i=0;i<x.length;i++)v.setUint8(o++,x.charCodeAt(i))};s('RIFF');v.setUint32(o,36+len,true);o+=4;s('WAVEfmt ');v.setUint32(o,16,true);o+=4;v.setUint16(o,1,true);o+=2;v.setUint16(o,ch,true);o+=2;v.setUint32(o,buffer.sampleRate,true);o+=4;v.setUint32(o,buffer.sampleRate*ch*2,true);o+=4;v.setUint16(o,ch*2,true);o+=2;v.setUint16(o,16,true);o+=2;s('data');v.setUint32(o,len,true);o+=4;for(let i=0;i<buffer.length;i++)for(let c=0;c<ch;c++){let x=Math.max(-1,Math.min(1,buffer.getChannelData(c)[i]));v.setInt16(o,x<0?x*32768:x*32767,true);o+=2}return new Blob([ab],{type:'audio/wav'})}
$('exportMix').onclick=async()=>{try{$('mixStatus').textContent='Rendering processed WAV locally…';const tmp=new (window.AudioContext||window.webkitAudioContext)();const tracks=await decodeTracks(tmp);await tmp.close();const duration=Math.max(...tracks.map(t=>t.buffer.duration));const rate=tracks[0].buffer.sampleRate||48000;const off=new OfflineAudioContext(2,Math.ceil(duration*rate),rate);const master=buildMaster(off,off.destination);tracks.forEach(t=>{const src=off.createBufferSource(),g=off.createGain(),pan=off.createStereoPanner();src.buffer=t.buffer;g.gain.value=Number(t.row.querySelector('.track-vol').value);pan.pan.value=Number(t.row.querySelector('.track-pan').value);src.connect(g).connect(pan).connect(master);src.start(0)});const rendered=await off.startRendering();const blob=encodeWav(rendered),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='RIVANI-Music-Master.wav';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);$('mixStatus').textContent='Processed WAV exported.'}catch(e){$('mixStatus').textContent=e.message}};
boot();})();